USE [Escola]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASSE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CLASSE] [varchar](180) NULL,
	[TIPO_ENSINO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASSE]  WITH CHECK ADD  CONSTRAINT [fk_TIPO_ENSINO] FOREIGN KEY([TIPO_ENSINO])
REFERENCES [dbo].[NIVEL_ENSINO] ([ID])
GO

ALTER TABLE [dbo].[CLASSE] CHECK CONSTRAINT [fk_TIPO_ENSINO]
GO


